remote_theme: daattali/beautiful-jekyll

title: PhaPass
layout: post
subtitle: A password manager using Phala
author: Laurent Turek
gh-repo: LaurentTrk/phapass
gh-badge: [ star ] 
title-img: /phala-34.png

navbar-links:
  Encode Polkadot Hackathon: "https://www.encode.club/polkadot-club-hackathon"
  Phala Network: "https://phala.network"
  About Me: "https://www.linkedin.com/in/laurenttrk"

  
social-network-links:
  github: LaurentTrk
  twitter: LaurentTrk
  linkedin: LaurentTrk
