remote_theme: daattali/beautiful-jekyll

title: PhaPass
layout: post
subtitle: A password manager using Phala
author: Laurent Turek
gh-repo: LaurentTrk/phapass
gh-badge: [ star ] 
# title-img: /ltk_black_sticker.png
title-img: /phala-128.png
# avatar: /phala-128.png

navbar-links:
  Encode Polkadot Hackathon: "https://www.encode.club/polkadot-club-hackathon"
  Phala Network: "https://phala.network"
  About Me: "https://www.linkedin.com/in/laurenttrk"

# navbar-col: "#FFDC09"  
# navbar-text-col: "#404040"
# navbar-border-col: "#DDDDDD"
# page-col: "#FFFFFF"
# text-col: "#404040"
# link-col: "#008AFF"
# hover-col: "#0085A1"
# footer-col: "#FFDC09"
# footer-text-col: "#777777"
# footer-link-col: "#404040"
# footer-hover-col: "#0085A1"

social-network-links:
  github: LaurentTrk
  twitter: LaurentTrk
  linkedin: LaurentTrk
